# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VWorldDockWidget
                                 A QGIS plugin
 QGIS에서 브이월드를 쉽게 활용할 수 있도록 기능제공
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2024 by spaceN.or.kr
        email                : dy.lee@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys
import requests
import json

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, Qt
from PyQt5.QtCore import QVariant
from qgis.core import QgsPoint, QgsFeature, QgsGeometry, QgsPointXY, QgsProject, QgsVectorLayer, QgsField, QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsJsonUtils, QgsMultiPolygon, QgsPolygon, QgsLineString
from qgis.PyQt.QtWidgets import QListWidgetItem, QMenu, QDialog, QVBoxLayout, QLineEdit
from qgis.utils import iface

from .public import public

plugin_dir = os.path.dirname(__file__)
sys.path.append(plugin_dir)
from config import API_KEY


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ui/v_world_dockSearch_base.ui'))


class VWorldDockSearch(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(VWorldDockSearch, self).__init__(parent)
        self.setupUi(self)
        self.listSearch.itemDoubleClicked.connect(self.on_listSearch_itemClicked)
        self.recentSearchs.itemDoubleClicked.connect(self.on_recentSearchs_itemClicked)

        self.inputSearch.editingFinished.connect(self.on_inputSearch_finished)


        #주소 검색 패널에서 아이템 우클릭 시 메뉴 생성
        self.listSearch.setContextMenuPolicy(Qt.CustomContextMenu)
        self.listSearch.customContextMenuRequested.connect(self.showContextMenuForListSearch)

        #최근 검색 패널에서 아이템 우클릭 시 메뉴 생성
        self.recentSearchs.setContextMenuPolicy(Qt.CustomContextMenu)
        self.recentSearchs.customContextMenuRequested.connect(self.showContextMenuForRecentSearch)


        self.refreshSearches()

    def showContextMenuForListSearch(self, position):
        # 우클릭한 아이템을 찾습니다.
        item = self.listSearch.itemAt(position)
        if not item:
            return  # 아이템이 없으면 메뉴를 표시하지 않습니다.

        # 컨텍스트 메뉴 생성
        menu = QMenu()
        addFavorites = menu.addAction("주소 복사하기")

        # 액션에 대한 신호를 슬롯에 연결할 수 있습니다.
        addFavorites.triggered.connect(self.addrCopyPopup)

        # 메뉴를 표시
        menu.exec_(self.listSearch.viewport().mapToGlobal(position))

    def showContextMenuForRecentSearch(self, position):
        item = self.recentSearchs.itemAt(position)
        if not item:
            return  # 아이템이 없으면 메뉴를 표시하지 않습니다.

        # 컨텍스트 메뉴 생성
        menu = QMenu()
        addFavorites = menu.addAction("주소 복사하기")

        # 액션에 대한 신호를 슬롯에 연결할 수 있습니다.
        addFavorites.triggered.connect(self.addrCopyPopupRecentSearch)

        # 메뉴를 표시
        menu.exec_(self.recentSearchs.viewport().mapToGlobal(position))

    def addrCopyPopup(self):
        # 선택한 아이템의 텍스트를 가져옵니다.
        selectedItemText = self.listSearch.currentItem().text()

        # 팝업 대화상자를 생성합니다.
        dialog = QDialog()
        dialog.setWindowTitle("주소 복사하기")

        # QLineEdit 위젯을 생성하고, 선택한 아이템의 텍스트를 설정합니다.
        lineEdit = QLineEdit(dialog)
        lineEdit.setText(selectedItemText)

        # 대화상자에 QVBoxLayout를 설정하고, QLineEdit 위젯을 추가합니다.
        layout = QVBoxLayout()
        layout.addWidget(lineEdit)
        dialog.setLayout(layout)

        # 팝업 대화상자를 모달로 표시합니다.
        dialog.exec_()

    def addrCopyPopupRecentSearch(self):
        # 선택한 아이템의 텍스트를 가져옵니다.
        selectedItemText = self.recentSearchs.currentItem().text()

        # 팝업 대화상자를 생성합니다.
        dialog = QDialog()
        dialog.setWindowTitle("주소 복사하기")

        # QLineEdit 위젯을 생성하고, 선택한 아이템의 텍스트를 설정합니다.
        lineEdit = QLineEdit(dialog)
        lineEdit.setText(selectedItemText)

        # 대화상자에 QVBoxLayout를 설정하고, QLineEdit 위젯을 추가합니다.
        layout = QVBoxLayout()
        layout.addWidget(lineEdit)
        dialog.setLayout(layout)

        # 팝업 대화상자를 모달로 표시합니다.
        dialog.exec_()



    #QlineEdit인 inputSearch에 값이 변경될 때 마다 호출되는 함수
    def on_inputSearch_finished(self):

        text = self.inputSearch.text()
        crs = QgsProject.instance().crs().authid()
        # iface.messageBar().pushMessage(f"검색어: {crs}", level=0)

        #입력된 값이 없으면 함수를 종료
        if text == "":
            return
        else:

            searchList = []


            returnProtocol = public.return_protocol(self)
            apiurl = returnProtocol[0] + "api.vworld.kr/req/search?"
            params = {
                "key": API_KEY,
                "request": "search",
                "format": "json",
                "size": "10",
                "page": "1",
                "query": text,
                "type": "ADDRESS",
                "category": "PARCEL",
                "crs": crs
            }
            try:
                response = requests.get(apiurl, params=params, verify=returnProtocol[1])
                # iface.messageBar().pushMessage(f"검색 URL: {response.url}", level=0)

                if response.status_code == 200:
                    data = response.json()  # JSON 데이터 파싱
                    self.listSearch.clear()
                    if data['response']['status'] != 'NOT_FOUND':
                        for item in data['response']['result']['items']:
                            searchList.append([item['address']['parcel'], [item['point']['x'], item['point']['y']]])
                    else:
                        params['category'] = 'ROAD'
                        response = requests.get(apiurl, params=params, verify=returnProtocol[1])
                        data = response.json()
                        if data['response']['status'] != 'NOT_FOUND':
                            for item in data['response']['result']['items']:
                                searchList.append([item['address']['road'], [item['point']['x'], item['point']['y']]])
                                # iface.messageBar().pushMessage(f"검색 결과: {[item['address']['road'], [item['point']['x'], item['point']['y']]]}", level=0)
                        else:
                            apiurls = returnProtocol[0] + "api.vworld.kr/req/data?"
                            paramss = {
                                "service": "data",
                                "request": "GetFeature",
                                "data": "LT_C_LANDINFOBASEMAP",
                                "key": API_KEY,
                                "crs": crs,
                                "size": "10",
                                "attrFilter": f"pnu:like:{text.replace(' ', '')}"
                            }
                            responses = requests.get(apiurls, params=paramss, verify=returnProtocol[1])
                            if responses.status_code == 200:
                                datas = responses.json()
                                if datas['response']['status'] != 'NOT_FOUND':
                                    for items in datas['response']['result']['featureCollection']['features']:

                                        multi_polygon_coordinates = items['geometry']['coordinates']
                                        multi_polygon = QgsMultiPolygon()

                                        for polygon_coordinates in multi_polygon_coordinates:
                                            points = [QgsPoint(coord[0], coord[1]) for coord in polygon_coordinates[0]]
                                            outer_ring = QgsLineString(points)
                                            polygon = QgsPolygon()
                                            polygon.setExteriorRing(outer_ring)
                                            multi_polygon.addGeometry(polygon)

                                        # QgsGeometry 객체를 생성할 때 멀티폴리곤 인스턴스를 사용
                                        multi_polygon_geom = QgsGeometry(multi_polygon)

                                        # 멀티폴리곤의 내부에 위치한 점 찾기
                                        point_on_surface = multi_polygon_geom.pointOnSurface()

                                        # point_on_surface.asWkt() 을 str로 split 하여 좌표 추출
                                        x = float(point_on_surface.asWkt().split(" ")[1].replace("(", ""))
                                        y = float(point_on_surface.asWkt().split(" ")[2].replace(")", ""))

                                        addrJoin = f"{items['properties']['sido_nm']} {items['properties']['sgg_nm']} {items['properties']['emd_nm']} {items['properties']['ri_nm']} {items['properties']['jibun']}".replace("  ", " ")

                                        searchList.append([f"{items['properties']['pnu']}({addrJoin})", [x, y]])
                    if searchList:
                        for item in searchList:
                            #item[0]에 중복이 있는지
                            if item[0] not in [self.listSearch.item(i).text() for i in range(self.listSearch.count())]:
                                self.listSearch.addItem(f"{item[0]}")
                                self.listSearch.item(self.listSearch.count() - 1).setData(Qt.UserRole, item[1][0])
                                self.listSearch.item(self.listSearch.count() - 1).setData(Qt.UserRole + 1, item[1][1])
                            # else:
                            #     iface.messageBar().pushMessage(f"검색 결과 중복: {item[0]}[{item[1][0]}, {item[1][1]}]", level=0)
                    else:
                        self.listSearch.addItem("검색 결과 없음")
            except requests.exceptions.SSLError as e:
                public.showMessage_sslConnectError(self)

    def on_recentSearchs_itemClicked(self, item):
        # 프로젝트의 현재 CRS를 가져옴
        project_crs = QgsProject.instance().crs().authid()
        # 클릭된 아이템의 데이터를 가져옴
        x = item.data(Qt.UserRole)
        y = item.data(Qt.UserRole + 1)
        # 좌표계 정보
        epsg = item.data(Qt.UserRole + 2)

        if project_crs != epsg:
            sourceCrs = QgsCoordinateReferenceSystem(epsg)
            destCrs = QgsProject.instance().crs()
            transform = QgsCoordinateTransform(sourceCrs, destCrs, QgsProject.instance())

            # 변환
            point = transform.transform(QgsPointXY(x, y))
            x, y = point.x(), point.y()

        # 이동
        center = QgsPointXY(x, y)
        iface.mapCanvas().setCenter(center)
        iface.mapCanvas().refresh()
        iface.mapCanvas().zoomScale(3000)

        self.searchLayer(x, y, item.text())

    def on_listSearch_itemClicked(self, item):
        # 프로젝트의 현재 CRS를 가져옴
        project_crs = QgsProject.instance().crs().authid()
        x = item.data(Qt.UserRole)
        y = item.data(Qt.UserRole + 1)
        # 문자열을 실수형으로 변환
        x_float = float(x)
        y_float = float(y)

        searches_path = os.path.join(os.path.dirname(__file__), "datas", "recent_searches.json")
        # 디렉토리가 없다면 생성
        os.makedirs(os.path.dirname(searches_path), exist_ok=True)

        # 파일이 없다면 빈 JSON 파일 생성
        if not os.path.exists(searches_path):
            with open(searches_path, "w", encoding='utf-8') as f:
                json.dump({}, f, ensure_ascii=False)
        with open(searches_path, "r") as f:
            searches = json.load(f)

        searches = {item.text(): [x_float, y_float, project_crs], **searches}
        if len(searches) > 10:
            searches.pop(list(searches.keys())[-1])

        with open(searches_path, "w", encoding='utf-8') as f:
            json.dump(searches, f, indent=4, ensure_ascii=False)


        # 새 중심점 생성
        center = QgsPointXY(x_float, y_float)
        iface.mapCanvas().setCenter(center)
        iface.mapCanvas().refresh()
        iface.mapCanvas().zoomScale(3000)

        self.searchLayer(x_float, y_float, item.text())

        self.refreshSearches()

    def searchLayer(self, x, y, name):
        project_crs = QgsProject.instance().crs().authid()

        # "브이월드[주소결과]" 이름을 가진 레이어가 이미 존재하는지 확인
        lyrName = "브이월드[주소결과]"
        lyrExists = QgsProject.instance().mapLayersByName(lyrName)

        if not lyrExists:

            self.lyr = QgsVectorLayer(f"Point?crs={project_crs}", lyrName, "memory")
            self.lyrProvider = self.lyr.dataProvider()

            # addr 필드 추가
            self.lyrProvider.addAttributes([QgsField("addr", QVariant.String)])
            self.lyr.updateFields()  # 필드 변경 사항을 레이어에 적용

            QgsProject.instance().addMapLayer(self.lyr)  # 레이어를 프로젝트에 추가

        else:
            self.lyr = lyrExists[0]  # 레이어가 이미 존재하면, 그 레이어를 사용
            self.lyrProvider = self.lyr.dataProvider()

            if self.lyr.crs().authid() != project_crs:
                self.lyr.startEditing()
                for feat in self.lyr.getFeatures():
                    geom = feat.geometry()
                    geom.transform(QgsCoordinateTransform(self.lyr.crs(), QgsCoordinateReferenceSystem(project_crs),
                                                          QgsProject.instance()))
                    self.lyr.changeGeometry(feat.id(), geom)
                self.lyr.commitChanges()
                self.lyr.setCrs(QgsCoordinateReferenceSystem(project_crs))
                self.lyr.updateExtents()

        # x y 좌표를 이용하여 QgsGeometry 객체 생성
        geom = QgsGeometry.fromPointXY(QgsPointXY(x, y))
        # 레이어에 새 피처 추가
        feat = QgsFeature()
        feat.setGeometry(geom)
        feat.setAttributes([name])
        self.lyrProvider.addFeatures([feat])
        self.lyr.updateExtents()
        iface.mapCanvas().refresh()

    def refreshSearches(self):
        self.recentSearchs.clear()
        searches_path = os.path.join(os.path.dirname(__file__), "datas", "recent_searches.json")
        if os.path.exists(searches_path):
            with open(searches_path, "r") as f:
                searches = json.load(f)
                for key, value in searches.items():
                    item = QtWidgets.QListWidgetItem(f"{key}")
                    item.setData(Qt.UserRole, value[0])
                    item.setData(Qt.UserRole + 1, value[1])
                    self.recentSearchs.addItem(item)


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()