# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VWorldDockWidget
                                 A QGIS plugin
 QGIS에서 브이월드를 쉽게 활용할 수 있도록 기능제공
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2024 by spaceN.or.kr
        email                : dy.lee@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys

from qgis.core import QgsRasterLayer, QgsProject
from qgis.utils import iface

plugin_dir = os.path.dirname(__file__)
sys.path.append(plugin_dir)
from config import API_KEY

def addWmtsLayer(layerType):
	# WMTS Capabilities URL
	capabilitiesUrl = f"http://api.vworld.kr/req/wmts/1.0.0/{API_KEY}/WMTSCapabilities.xml"

	# WMTS 레이어에 필요한 파라미터 설정
	layerName = layerType
	tileMatrixSet = "GoogleMapsCompatible"  # 타일 매트릭스 세트
	imageFormat = "image/png" if layerType == "Base" or layerType == "Hybrid" else "image/jpeg"

	# QgsRasterLayer 객체 생성을 위한 URI 구성
	uri = f"crs=EPSG:3857&dpiMode=7&format={imageFormat}&layers={layerName}&styles=default&tileMatrixSet={tileMatrixSet}&url={capabilitiesUrl}"

	# QgsRasterLayer 객체 생성
	wmtsLayer = QgsRasterLayer(uri, f"브이월드 지도[{layerType}]", "wms")

	# 레이어 유효성 검사
	if not wmtsLayer.isValid():
		iface.messageBar().pushMessage("오류", "배경지도를 불러오는 중 오류가 발생했습니다.", level=2)
		return

	# 현재 QGIS 프로젝트에 레이어 추가
	QgsProject.instance().addMapLayer(wmtsLayer)
